/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { Box } from "../Common";

export default function CdmModel(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(GLB_ASSET_URLS.CDM);
    const { actions } = useAnimations(animations, group);
    return (
        <Box {...props}>
            <group ref={group} dispose={null}>
                <group name="Scene">
                    <group name="cdm">
                        <group name="rotation_null006">
                            <mesh
                                name="gasket"
                                castShadow
                                receiveShadow
                                geometry={nodes.gasket.geometry}
                                material={nodes.gasket.material}
                                morphTargetDictionary={
                                    nodes.gasket.morphTargetDictionary
                                }
                                morphTargetInfluences={
                                    nodes.gasket.morphTargetInfluences
                                }
                                position={[-0.003, -0.265, -0.005]}
                            />
                            <mesh
                                name="joystick003"
                                castShadow
                                receiveShadow
                                geometry={nodes.joystick003.geometry}
                                material={nodes.joystick003.material}
                                position={[-0.003, -0.265, -0.005]}
                            >
                                <mesh
                                    name="joystick001"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.joystick001.geometry}
                                    material={nodes.joystick001.material}
                                    position={[0, 0.075, 0.02]}
                                />
                            </mesh>
                        </group>
                    </group>
                </group>
            </group>
        </Box>
    );
}

useGLTF.preload(GLB_ASSET_URLS.CDM);
