/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { Box } from "../Common";

export default function EpbModel(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(GLB_ASSET_URLS.EPB);
    const { actions } = useAnimations(animations, group);
    return (
        <Box {...props}>
            <group ref={group} dispose={null}>
                <group name="Scene">
                    <group name="epb">
                        <group name="rotation_null013">
                            <mesh
                                name="bolt001"
                                castShadow
                                receiveShadow
                                geometry={nodes.bolt001.geometry}
                                material={nodes.bolt001.material}
                                morphTargetDictionary={
                                    nodes.bolt001.morphTargetDictionary
                                }
                                morphTargetInfluences={
                                    nodes.bolt001.morphTargetInfluences
                                }
                                position={[-0.024, 0.093, 0.006]}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </Box>
    );
}

useGLTF.preload(GLB_ASSET_URLS.EPB);
