/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { Box } from "../Common";

export default function EyeModel(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(GLB_ASSET_URLS.Eye);
    const { actions } = useAnimations(animations, group);
    return (
        <Box {...props}>
            <group ref={group} dispose={null}>
                <group name="Scene">
                    <group name="eye">
                        <group name="rotation_null008">
                            <mesh
                                name="eye001"
                                castShadow
                                receiveShadow
                                geometry={nodes.eye001.geometry}
                                material={nodes.eye001.material}
                                morphTargetDictionary={
                                    nodes.eye001.morphTargetDictionary
                                }
                                morphTargetInfluences={
                                    nodes.eye001.morphTargetInfluences
                                }
                            >
                                <mesh
                                    name="iris"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.iris.geometry}
                                    material={nodes.iris.material}
                                    morphTargetDictionary={
                                        nodes.iris.morphTargetDictionary
                                    }
                                    morphTargetInfluences={
                                        nodes.iris.morphTargetInfluences
                                    }
                                />
                            </mesh>
                        </group>
                    </group>
                </group>
            </group>
        </Box>
    );
}

useGLTF.preload(GLB_ASSET_URLS.Eye);
