/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { Box } from "../Common";

export default function GyroModel(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(GLB_ASSET_URLS.Gyro);
    const { actions } = useAnimations(animations, group);
    return (
        <Box {...props}>
            <group ref={group} dispose={null}>
                <group name="Scene">
                    <group name="gyro">
                        <group name="rotation_null009">
                            <mesh
                                name="gyro001"
                                castShadow
                                receiveShadow
                                geometry={nodes.gyro001.geometry}
                                material={nodes.gyro001.material}
                                position={[0, -0.657, 0.001]}
                                rotation={[0.028, -0.08, -0.015]}
                            >
                                <mesh
                                    name="axis"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.axis.geometry}
                                    material={nodes.axis.material}
                                    position={[0.002, 0.656, 0]}
                                    rotation={[0, -0.585, 0]}
                                />
                            </mesh>
                        </group>
                    </group>
                </group>
            </group>
        </Box>
    );
}

useGLTF.preload(GLB_ASSET_URLS.Gyro);
