/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { Box } from "../Common";

export default function KeyModel(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(GLB_ASSET_URLS.Key);
    const { actions } = useAnimations(animations, group);
    return (
        <Box {...props}>
            <group ref={group} dispose={null}>
                <group name="Scene">
                    <group name="key">
                        <group name="rotation_null001">
                            <mesh
                                name="key001"
                                castShadow
                                receiveShadow
                                geometry={nodes.key001.geometry}
                                material={nodes.key001.material}
                                position={[-0.156, -0.34, 0.002]}
                            />
                            <mesh
                                name="key002"
                                castShadow
                                receiveShadow
                                geometry={nodes.key002.geometry}
                                material={nodes.key002.material}
                                position={[0.201, 0.316, 0.003]}
                            />
                            <mesh
                                name="key003"
                                castShadow
                                receiveShadow
                                geometry={nodes.key003.geometry}
                                material={nodes.key003.material}
                                position={[-0.353, -0.308, 0.002]}
                            />
                            <mesh
                                name="key004"
                                castShadow
                                receiveShadow
                                geometry={nodes.key004.geometry}
                                material={nodes.key004.material}
                                position={[0.357, 0.274, 0.006]}
                            />
                            <mesh
                                name="key005"
                                castShadow
                                receiveShadow
                                geometry={nodes.key005.geometry}
                                material={nodes.key005.material}
                                position={[0.472, 0.336, 0.007]}
                            />
                            <mesh
                                name="key006"
                                castShadow
                                receiveShadow
                                geometry={nodes.key006.geometry}
                                material={nodes.key006.material}
                                position={[-0.34, -0.517, 0.002]}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </Box>
    );
}

useGLTF.preload(GLB_ASSET_URLS.Key);
