/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useCallback, useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { Box } from "../Common";

export default function MethodsModel(props) {
    const [mounted, setMounted] = useState(false);
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(GLB_ASSET_URLS.Methods);
    const { actions, names } = useAnimations(animations, group);

    const handleClick = useCallback(() => {
        actions?.gear_01?.reset().play();
        actions?.gear_02?.reset().play();
    }, [actions]);

    useEffect(() => {
        if (!mounted) return;
        if (Object.keys(actions).length === 0) return;
        names.forEach((name) => {
            const action = actions[name];
            switch (name) {
                case "methods_orbit":
                    action.play();
                    break;
                case "gear_01":
                case "gear_02":
                    action.loop = THREE.LoopOnce;
                    break;
                default:
                    break;
            }
        });
    }, [mounted, actions, names]);

    useEffect(() => {
        setMounted(true);
    }, []);
    return (
        <Box {...props}>
            <group ref={group} dispose={null} onClick={handleClick}>
                <group name="Scene">
                    <group name="methods">
                        <group name="rotation_null005">
                            <group name="shaft" rotation={[-0.175, 0, 0]}>
                                <mesh
                                    name="Cylinder002"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder002.geometry}
                                    material={nodes.Cylinder002.material}
                                />
                                <mesh
                                    name="Cylinder002_1"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder002_1.geometry}
                                    material={nodes.Cylinder002_1.material}
                                />
                                <mesh
                                    name="gear_01"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.gear_01.geometry}
                                    material={nodes.gear_01.material}
                                    position={[-0.264, -0.152, 0]}
                                />
                                <mesh
                                    name="gear_02"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.gear_02.geometry}
                                    material={nodes.gear_02.material}
                                    position={[0, 0.305, 0]}
                                />
                                <mesh
                                    name="gear_03"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.gear_03.geometry}
                                    material={nodes.gear_03.material}
                                    position={[0.264, -0.152, 0]}
                                />
                                <mesh
                                    name="gear_04"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.gear_04.geometry}
                                    material={nodes.gear_04.material}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </Box>
    );
}

useGLTF.preload(GLB_ASSET_URLS.Methods);
