/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { Box } from "../Common";

export default function NorthfaceModel(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(GLB_ASSET_URLS.Northface);
    const { actions } = useAnimations(animations, group);
    return (
        <Box {...props}>
            <group ref={group} dispose={null}>
                <group name="Scene">
                    <group name="northface">
                        <group name="rotation_null011">
                            <mesh
                                name="Plane001"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane001.geometry}
                                material={nodes.Plane001.material}
                                morphTargetDictionary={
                                    nodes.Plane001.morphTargetDictionary
                                }
                                morphTargetInfluences={
                                    nodes.Plane001.morphTargetInfluences
                                }
                            />
                        </group>
                    </group>
                </group>
            </group>
        </Box>
    );
}

useGLTF.preload(GLB_ASSET_URLS.Northface);
