/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useCallback, useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { Box } from "../Common";

export default function WorkModel(props) {
    const [mounted, setMounted] = useState(false);
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(GLB_ASSET_URLS.Work);
    const { actions, names } = useAnimations(animations, group);

    const handleClick = useCallback(() => {
        actions?.glove.reset().play();
    }, [actions]);

    useEffect(() => {
        if (!mounted) return;
        if (Object.keys(actions).length === 0) return;
        names.forEach((name) => {
            const action = actions[name];
            switch (name) {
                case "work_orbit":
                    action.play();
                    break;
                case "glove":
                    action.loop = THREE.LoopOnce;
                    break;
                default:
                    break;
            }
        });
    }, [mounted, actions, names]);

    useEffect(() => {
        setMounted(true);
    }, []);
    return (
        <Box {...props}>
            <group ref={group} dispose={null} onClick={handleClick}>
                <group name="Scene">
                    <group name="work">
                        <group name="rotation_null002">
                            <mesh
                                name="Hand_-_Stylized_"
                                castShadow
                                receiveShadow
                                geometry={nodes["Hand_-_Stylized_"].geometry}
                                material={nodes["Hand_-_Stylized_"].material}
                                morphTargetDictionary={
                                    nodes["Hand_-_Stylized_"]
                                        .morphTargetDictionary
                                }
                                morphTargetInfluences={
                                    nodes["Hand_-_Stylized_"]
                                        .morphTargetInfluences
                                }
                                position={[0.026, -0.067, -0.021]}
                            >
                                <mesh
                                    name="tie"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.tie.geometry}
                                    material={nodes.tie.material}
                                    morphTargetDictionary={
                                        nodes.tie.morphTargetDictionary
                                    }
                                    morphTargetInfluences={
                                        nodes.tie.morphTargetInfluences
                                    }
                                />
                            </mesh>
                        </group>
                    </group>
                </group>
            </group>
        </Box>
    );
}

useGLTF.preload(GLB_ASSET_URLS.Work);
