/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { Box } from "../Common";

export default function WorkModel(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(GLB_ASSET_URLS.Work);
    const { actions } = useAnimations(animations, group);
    return (
        <Box {...props}>
            <group ref={group} dispose={null}>
                <group name="Scene">
                    <group name="work">
                        <group name="rotation_null002">
                            <mesh
                                name="Hand_-_Stylized_"
                                castShadow
                                receiveShadow
                                geometry={nodes["Hand_-_Stylized_"].geometry}
                                material={nodes["Hand_-_Stylized_"].material}
                                morphTargetDictionary={
                                    nodes["Hand_-_Stylized_"]
                                        .morphTargetDictionary
                                }
                                morphTargetInfluences={
                                    nodes["Hand_-_Stylized_"]
                                        .morphTargetInfluences
                                }
                                position={[0.026, -0.067, -0.021]}
                            >
                                <mesh
                                    name="tie"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.tie.geometry}
                                    material={nodes.tie.material}
                                    morphTargetDictionary={
                                        nodes.tie.morphTargetDictionary
                                    }
                                    morphTargetInfluences={
                                        nodes.tie.morphTargetInfluences
                                    }
                                />
                            </mesh>
                        </group>
                    </group>
                </group>
            </group>
        </Box>
    );
}

useGLTF.preload(GLB_ASSET_URLS.Work);
