/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useCallback, useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { GrainMaterialRed, OutlineMaterial } from "../Materials";

export default function EpbModel({ opacity = 1, ...props }) {
    const [mounted, setMounted] = useState(false);
    const [boundingBox, setBoundingBox] = useState({
        min: new THREE.Vector3(0, 0, 0),
        max: new THREE.Vector3(1, 1, 1),
    });
    const group = useRef();
    const { nodes, animations } = useGLTF(GLB_ASSET_URLS.EPB);
    const { actions, names } = useAnimations(animations, group);

    const handleClick = useCallback(() => {
        actions?.bolt_01.reset().play();
        actions?.bolt_02.reset().play();
    }, [actions]);

    useEffect(() => {
        if (!mounted) return;
        if (Object.keys(actions).length === 0) return;
        names.forEach((name) => {
            const action = actions[name];
            switch (name) {
                case "epb_orbit":
                    action.play();
                    break;
                case "bolt_01":
                case "bolt_02":
                    action.loop = THREE.LoopOnce;
                    break;
                default:
                    break;
            }
        });
    }, [mounted, actions, names]);

    // setup uniforms
    useEffect(() => {
        const bb = new THREE.Box3();
        bb.setFromObject(group.current);
        setBoundingBox(bb);
    }, []);

    useEffect(() => {
        setMounted(true);
    }, []);
    return (
        <group
            {...props}
            name="EpbModel"
            ref={group}
            dispose={null}
            onClick={handleClick}
        >
            <group name="Scene">
                <group name="epb">
                    <group name="rotation_null013">
                        <mesh
                            name="bolt"
                            geometry={nodes.bolt.geometry}
                            //   material={materials.green_01}
                            morphTargetDictionary={
                                nodes.bolt.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.bolt.morphTargetInfluences
                            }
                            position={[-0.024, 0.093, 0.006]}
                        >
                            <GrainMaterialRed
                                opacity={opacity}
                                boundingBox={boundingBox}
                            />
                        </mesh>
                        <mesh
                            name="bolt_outline"
                            geometry={nodes.bolt_outline.geometry}
                            //   material={materials.outline}
                            morphTargetDictionary={
                                nodes.bolt_outline.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.bolt_outline.morphTargetInfluences
                            }
                            position={[-0.024, 0.093, 0.006]}
                        >
                            <OutlineMaterial opacity={opacity} />
                        </mesh>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload(GLB_ASSET_URLS.EPB);
