/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useCallback, useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { GrainMaterialViolet } from "../Materials";

export default function EyeModel(props) {
    const [mounted, setMounted] = useState(false);
    const [boundingBox, setBoundingBox] = useState({
        min: new THREE.Vector3(0, 0, 0),
        max: new THREE.Vector3(1, 1, 1),
    });
    const group = useRef();
    const { nodes, animations } = useGLTF(GLB_ASSET_URLS.Eye);
    const { actions, names } = useAnimations(animations, group);

    const handleClick = useCallback(() => {
        actions?.pupil.reset().play();
    }, [actions]);

    useEffect(() => {
        if (!mounted) return;
        if (Object.keys(actions).length === 0) return;
        names.forEach((name) => {
            const action = actions[name];
            switch (name) {
                case "pupil":
                    action.loop = THREE.LoopOnce;
                    break;
                default:
                    break;
            }
        });
    }, [mounted, actions, names]);

    // setup uniforms
    useEffect(() => {
        const bb = new THREE.Box3();
        bb.setFromObject(group.current);
        setBoundingBox(bb);
    }, []);

    useEffect(() => {
        setMounted(true);
    }, []);
    return (
        <group ref={group} {...props} dispose={null} onClick={handleClick}>
            <group name="Scene">
                <group name="eye">
                    <group name="rotation_null008">
                        <mesh
                            name="eye001"
                            castShadow
                            receiveShadow
                            geometry={nodes.eye001.geometry}
                            // material={nodes.eye001.material}
                            morphTargetDictionary={
                                nodes.eye001.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.eye001.morphTargetInfluences
                            }
                        >
                            <GrainMaterialViolet boundingBox={boundingBox} />
                            <mesh
                                name="iris"
                                castShadow
                                receiveShadow
                                geometry={nodes.iris.geometry}
                                // material={nodes.iris.material}
                                morphTargetDictionary={
                                    nodes.iris.morphTargetDictionary
                                }
                                morphTargetInfluences={
                                    nodes.iris.morphTargetInfluences
                                }
                            >
                                <GrainMaterialViolet
                                    boundingBox={boundingBox}
                                />
                            </mesh>
                        </mesh>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload(GLB_ASSET_URLS.Eye);
