/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useCallback, useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { GrainMaterialRed } from "../Materials";

export default function SosModel(props) {
    const [mounted, setMounted] = useState(false);
    const [boundingBox, setBoundingBox] = useState({
        min: new THREE.Vector3(0, 0, 0),
        max: new THREE.Vector3(1, 1, 1),
    });
    const group = useRef();
    const { nodes, animations } = useGLTF(GLB_ASSET_URLS.SOS);
    const { actions, names } = useAnimations(animations, group);

    const handleClick = useCallback(() => {
        actions?.fish_02?.reset().play();
    }, [actions]);

    useEffect(() => {
        if (!mounted) return;
        if (Object.keys(actions).length === 0) return;
        names.forEach((name) => {
            const action = actions[name];
            switch (name) {
                case "fish_orbit":
                case "fish_01":
                case "bob":
                    action.play();
                    break;
                case "fish_02":
                    action.loop = THREE.LoopOnce;
                    break;
                default:
                    break;
            }
        });
    }, [mounted, actions, names]);

    // setup uniforms
    useEffect(() => {
        const bb = new THREE.Box3();
        bb.setFromObject(group.current);
        setBoundingBox(bb);
    }, []);

    useEffect(() => {
        setMounted(true);
    }, []);
    return (
        <group ref={group} {...props} dispose={null} onClick={handleClick}>
            <group name="Scene">
                <group name="sos">
                    <group name="rotation_null003">
                        <mesh
                            name="fish002"
                            castShadow
                            receiveShadow
                            geometry={nodes.fish002.geometry}
                            // material={nodes.fish002.material}
                            morphTargetDictionary={
                                nodes.fish002.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.fish002.morphTargetInfluences
                            }
                            position={[0.019, -0.075, 0.072]}
                            rotation={[0, -0.273, 0]}
                        >
                            <GrainMaterialRed boundingBox={boundingBox} />
                        </mesh>
                        <group
                            name="fish_02_holder"
                            position={[0, -0.075, 0]}
                            rotation={[0, -Math.PI / 6, 0]}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload(GLB_ASSET_URLS.SOS);
