/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useCallback, useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { GrainMaterialRed, OutlineMaterial } from "../Materials";

export default function SosModel({ opacity = 1, ...props }) {
    const [mounted, setMounted] = useState(false);
    const [boundingBox, setBoundingBox] = useState({
        min: new THREE.Vector3(0, 0, 0),
        max: new THREE.Vector3(1, 1, 1),
    });
    const group = useRef();
    const { nodes, animations } = useGLTF(GLB_ASSET_URLS.SOS);
    const { actions, names } = useAnimations(animations, group);

    const handleClick = useCallback(() => {
        actions?.blow_01?.reset().play();
        actions?.blow_02?.reset().play();
    }, [actions]);

    useEffect(() => {
        if (!mounted) return;
        if (Object.keys(actions).length === 0) return;
        names.forEach((name) => {
            const action = actions[name];
            switch (name) {
                case "fish_orbit":
                case "bob_01":
                case "bob_02":
                    action.play();
                    break;
                case "blow_01":
                case "blow_02":
                    action.loop = THREE.LoopOnce;
                    break;
                default:
                    break;
            }
        });
    }, [mounted, actions, names]);

    // setup uniforms
    useEffect(() => {
        const bb = new THREE.Box3();
        bb.setFromObject(group.current);
        setBoundingBox(bb);
    }, []);

    useEffect(() => {
        setMounted(true);
    }, []);
    return (
        <group ref={group} {...props} dispose={null} onClick={handleClick}>
            <group name="Scene">
                <group name="sos">
                    <group
                        name="rotation_null003"
                        position={[0, -0.153, 0.307]}
                        scale={0.972}
                    >
                        <mesh
                            name="fish"
                            geometry={nodes.fish.geometry}
                            //   material={materials.green_01}
                            morphTargetDictionary={
                                nodes.fish.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.fish.morphTargetInfluences
                            }
                            rotation={[0, -Math.PI / 6, 0]}
                            scale={0.777}
                        >
                            <GrainMaterialRed
                                opacity={opacity}
                                boundingBox={boundingBox}
                            />
                        </mesh>
                        <mesh
                            name="fish_outline"
                            geometry={nodes.fish_outline.geometry}
                            //   material={materials.outline}
                            morphTargetDictionary={
                                nodes.fish_outline.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.fish_outline.morphTargetInfluences
                            }
                            rotation={[0, -Math.PI / 6, 0]}
                            scale={0.777}
                        >
                            <OutlineMaterial opacity={opacity} />
                        </mesh>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload(GLB_ASSET_URLS.SOS);
