/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useCallback, useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { GrainMaterialYellow, GrainMaterialYellowDark } from "../Materials";

export default function WorkModel(props) {
    const [mounted, setMounted] = useState(false);
    const [boundingBox, setBoundingBox] = useState({
        min: new THREE.Vector3(0, 0, 0),
        max: new THREE.Vector3(1, 1, 1),
    });
    const group = useRef();
    const { nodes, animations } = useGLTF(GLB_ASSET_URLS.Work);
    const { actions, names } = useAnimations(animations, group);

    const handleClick = useCallback(() => {
        actions?.glove.reset().play();
    }, [actions]);

    useEffect(() => {
        if (!mounted) return;
        if (Object.keys(actions).length === 0) return;
        names.forEach((name) => {
            const action = actions[name];
            switch (name) {
                case "work_orbit":
                    action.play();
                    break;
                case "glove":
                    action.loop = THREE.LoopOnce;
                    break;
                default:
                    break;
            }
        });
    }, [mounted, actions, names]);

    // setup uniforms
    useEffect(() => {
        const bb = new THREE.Box3();
        bb.setFromObject(group.current);
        setBoundingBox(bb);
    }, []);

    useEffect(() => {
        setMounted(true);
    }, []);
    return (
        <group ref={group} {...props} dispose={null} onClick={handleClick}>
            <group name="Scene">
                <group name="work">
                    <group name="rotation_null002">
                        <mesh
                            name="Hand_-_Stylized_"
                            castShadow
                            receiveShadow
                            geometry={nodes["Hand_-_Stylized_"].geometry}
                            // material={nodes["Hand_-_Stylized_"].material}
                            morphTargetDictionary={
                                nodes["Hand_-_Stylized_"].morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes["Hand_-_Stylized_"].morphTargetInfluences
                            }
                            position={[0.026, -0.067, -0.021]}
                        >
                            <GrainMaterialYellow boundingBox={boundingBox} />
                            <mesh
                                name="tie"
                                castShadow
                                receiveShadow
                                geometry={nodes.tie.geometry}
                                // material={nodes.tie.material}
                                morphTargetDictionary={
                                    nodes.tie.morphTargetDictionary
                                }
                                morphTargetInfluences={
                                    nodes.tie.morphTargetInfluences
                                }
                            >
                                <GrainMaterialYellowDark
                                    boundingBox={boundingBox}
                                />
                            </mesh>
                        </mesh>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload(GLB_ASSET_URLS.Work);
