/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useCallback, useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { Box } from "../Scene/Common";

export default function Model(props) {
    const [mounted, setMounted] = useState(true);
    const group = useRef();
    const { nodes, animations } = useGLTF(GLB_ASSET_URLS.Culture);
    const { actions, names } = useAnimations(animations, group);

    const handleClick = useCallback(() => {
        actions?.explode_01.reset().play();
        actions?.explode_02.reset().play();
    }, [actions]);

    useEffect(() => {
        if (!mounted) return;
        if (Object.keys(actions).length === 0) return;
        names.forEach((name) => {
            const action = actions[name];
            switch (name) {
                case "culture_orbit":
                    action.play();
                    break;
                case "explode_01":
                case "explode_02":
                    action.clampWhenFinished = true; // stay on last frame
                    action.setLoop(THREE.LoopRepeat);
                    action.repetitions = 1;
                    break;
                default:
                    break;
            }
        });
    }, [mounted, actions, names]);

    useEffect(() => {
        setMounted(true);
    }, []);
    return (
        <Box {...props}>
            <group ref={group} dispose={null} onClick={handleClick}>
                <group name="Scene">
                    <group name="culture">
                        <group name="rotation_null015">
                            <mesh
                                name="camera001"
                                castShadow
                                receiveShadow
                                geometry={nodes.camera001.geometry}
                                material={nodes.camera001.material}
                                morphTargetDictionary={
                                    nodes.camera001.morphTargetDictionary
                                }
                                morphTargetInfluences={
                                    nodes.camera001.morphTargetInfluences
                                }
                                position={[0.033, -0.076, -0.111]}
                                rotation={[0, -Math.PI / 9, 0]}
                            >
                                <mesh
                                    name="frame"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.frame.geometry}
                                    material={nodes.frame.material}
                                    morphTargetDictionary={
                                        nodes.frame.morphTargetDictionary
                                    }
                                    morphTargetInfluences={
                                        nodes.frame.morphTargetInfluences
                                    }
                                />
                            </mesh>
                        </group>
                    </group>
                </group>
            </group>
        </Box>
    );
}

useGLTF.preload(GLB_ASSET_URLS.Culture);
