/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useCallback, useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

import { GLB_ASSET_URLS } from "@/js/core/constants";
import { Box } from "../Scene/Common";

export default function StoriesModel(props) {
    const [mounted, setMounted] = useState(false);
    const group = useRef();
    const { nodes, animations } = useGLTF(GLB_ASSET_URLS.Stories);
    const { actions, names } = useAnimations(animations, group);

    const handleClick = useCallback(() => {
        actions?.letter_01?.reset().play();
        actions?.letter_02?.reset().play();
        actions?.letter_03?.reset().play();
    }, [actions]);

    useEffect(() => {
        if (!mounted) return;
        if (Object.keys(actions).length === 0) return;
        names.forEach((name) => {
            const action = actions[name];
            switch (name) {
                case "stories_orbit":
                    action.play();
                    break;
                case "letter_01":
                case "letter_02":
                case "letter_03":
                    action.loop = THREE.LoopOnce;
                    break;
                default:
                    break;
            }
        });
    }, [mounted, actions, names]);

    useEffect(() => {
        setMounted(true);
    }, []);
    return (
        <Box {...props}>
            <group ref={group} dispose={null} onClick={handleClick}>
                <group name="Scene">
                    <group name="stories">
                        <group name="rotation_null010">
                            <mesh
                                name="Cube001"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube001.geometry}
                                material={nodes.Cube001.material}
                                position={[-0.152, -0.327, 0.498]}
                            >
                                <mesh
                                    name="tac"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.tac.geometry}
                                    material={nodes.tac.material}
                                />
                            </mesh>
                            <mesh
                                name="Cube002"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube002.geometry}
                                material={nodes.Cube002.material}
                                position={[0.239, -0.024, 0.417]}
                            >
                                <mesh
                                    name="cat"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.cat.geometry}
                                    material={nodes.cat.material}
                                />
                            </mesh>
                            <mesh
                                name="Cube003"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube003.geometry}
                                material={nodes.Cube003.material}
                                position={[-0.192, 0.273, 0.328]}
                            >
                                <mesh
                                    name="act"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.act.geometry}
                                    material={nodes.act.material}
                                />
                            </mesh>
                        </group>
                    </group>
                </group>
            </group>
        </Box>
    );
}

useGLTF.preload(GLB_ASSET_URLS.Stories);
